<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\Person;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // \App\Models\User::factory(10)->create();
        Storage::deleteDirectory('documents');
        Storage::createDirectory('documents');

        $person = new Person();
        $person->name ='ADUVIRE RAFAEL DIEGO NEWTON';
        $person->email = 'diego.adura@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='ARIAS QUISPE ELIZABETH VIVIANA';
        $person->email = 'ela_sabeth1420@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='BANEGAS YUGRA NATALY';
        $person->email = 'natalybanegas01@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CARPIO VALVERDE GLENDA LUCIA';
        $person->email = 'glendacarpio418@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CATACORA CACERES DIANA JACKELINE';
        $person->email = 'dianxelhix@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CENTENO SOTO LUCY';
        $person->email = 'darelltu1@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CERVANTES VIZCARRA GUILLERMO ANTONY';
        $person->email = 'antokita124@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CHAMA SIGUAYRO EMILIANA DORIS';
        $person->email = 'emilianacs12@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CHOQUE TAPIA ELIZABETH MARTA';
        $person->email = 'elimartha_cht@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CONDORI FUENTES BERLY EMIGDIO';
        $person->email = 'berlyecf@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CORDOVA IBARRA JULIA MARGARITA';
        $person->email = 'jmargaritacibarra@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='CORDOVA VILCA FRANK DUANER';
        $person->email = 'cordovavilcafrankduaner@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='ESTALLA CONDORI SOLEDAD';
        $person->email = 'khalessiquinonez0109@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='FALCON VIZCARRA YONILDE MAXI';
        $person->email = 'gabyescobarfalcon39@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='FRANCO INFANTAS RAINEIRO PATRICIO';
        $person->email = 'raineiropatricio21@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='GARCIA GUEVARA FIDENCIA ROSARIO';
        $person->email = 'rosaritoguevara2019@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='GONZALES RODRIGUEZ YULY MARY';
        $person->email = 'yul_mary2014@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='GUZMAN ITURRARAN URSULA IVANIA';
        $person->email = 'guzmanursula2@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='HEREDIA PINEDA CLAUDIA ISABEL';
        $person->email = 'clau.heredia@outlook.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='HUARAYA CHIPANA LUCINA CLARIT';
        $person->email = 'totitto30@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='LOZANO FERNANDEZ LIZBETH GENOVEVA';
        $person->email = 'lizbethlozanof@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='MAMANI ASENCIO JUBER ELVIO';
        $person->email = 'jm8687@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='MAMANI RODRIGUEZ ISMAEL';
        $person->email = 'ismaelmrodriguez18@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='MAQUERA ESPINOZA KAREN GORETY';
        $person->email = 'goretyespinoza23@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='MATOS SALAS PAOLO GIOVANNI';
        $person->email = 'pgmatoss@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='MEDINA DELGADO EDWIN';
        $person->email = 'gatinmd@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='MENDOZA MAMANI MIDWARD NEFI';
        $person->email = 'nefi2612@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='NUÑEZ DEL PRADO ROQUE ANDREA JENNY';
        $person->email = 'andrea.ndpr@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='PANOCCA QUISPE ROSMERY DELIA';
        $person->email = 'delyrouss7@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='PAREDES ROJAS ANA ISABEL';
        $person->email = 'ana.paredes.rojas90@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='PILCOMAMANI FLORES KARINA FRANCISCA';
        $person->email = 'kaylipilco13@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='QUISPE SUCASACA JUNIOR PIERO';
        $person->email = 'juniorgullo12@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RAMOS MURILLO CHRISTOPHER EFRAIN';
        $person->email = 'cristof.rm@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RANILLA CASTRO JENNY PATRICIA';
        $person->email = 'jennypatricia1092@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='REVILLA LLUTAHUI SKARLET JHUDY';
        $person->email = 'skarletjhudy425@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RIOS CHARCA LENNY ARACELI';
        $person->email = 'aracelyrios123@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RISCO VALDIVIESO EDGAR LUIS';
        $person->email = 'edgarisco@outlook.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RIVAS RIOS MARKO ANTONIO';
        $person->email = 'marko.rivas98@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RODRIGUEZ MAMANI EDITH ALEJANDRINA';
        $person->email = 'vida80127@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='RODRIGUEZ VARGAS LEENI DENIS';
        $person->email = 'leenirodriguez@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='ROJAS ORDOÑO DELICIA NORKA';
        $person->email = 'dely.girls.tk@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='ROJAS PACHECO MYRIAM BELEN';
        $person->email = 'rojasmyriam110@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='ROSADO CHAVEZ JACKELINE PAOLA';
        $person->email = 'jackelinerosadochavez@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='SALINAS MORON HERBERTH CAYETANO';
        $person->email = 'herber16_2009@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='SALVADOR LLACSAHUACHE SEBASTIAN';
        $person->email = 'salva25279@hotmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='VARGAS FLORES CLAUDIA KARINA';
        $person->email = 'claudiakarinavargas@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='VARGAS GAMERO NELSON DAVID';
        $person->email = 'nelsoonva@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='VENTURA GARAVITO CELIA DORIS';
        $person->email = 'cventuragaravito@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='VILLACORTA CHIRAPO TANIA EDITH';
        $person->email = 'taniavillacorta@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='YAIPEN FERNANDEZ-DAVILA RENZO MAXIMO';
        $person->email = 'renzo.yaipen14@gmail.com';
        $person->status = '1';
        $person->save();
$person = new Person();
        $person->name ='ZEPITA CHURA BERTHA MARIA';
        $person->email = 'bertha.zepita65@gmail.com';
        $person->status = '1';
        $person->save();

    }
}
